[ADD] 2024-01-22 - 云漏洞案例 | Unit42: GKE Autopilot 从容器逃逸到接管k8s集群并持久化后门
cloud-native-security-news/cloud-native-security-news pull request #70
Opened 2024-01-21 09:15 UTC by tarimoe

2024-01-22 05:59 UTC, ssst0n3 commented
一些疑问，留待研究：
* 为什么拒绝 External IP svc  可以防御 CVE-2020-8554
* GKE autopilot 如何拒绝External IP svc (PSA? OPA?)
* 也能防御 37c3 ctf 那道题的External IP svc 利用手法吗

2024-01-23 02:03 UTC, ssst0n3 requested changes
reviewed, request changes

2024-01-23 04:30 UTC, tarimoe commented on 2024-01-22_云漏洞案例_Unit42_GKE Autopilot 从容器逃逸到接管k8s集群并持久化后门.md
> +只要攻击者获取到了一个 Autopilot 的开发者账号，就能拿下整个k8s集群
对

2024-01-23 11:54 UTC, tarimoe commented on 2024-01-22_云漏洞案例_Unit42_GKE Autopilot 从容器逃逸到接管k8s集群并持久化后门.md
> +2. 攻击者可以查询节点的实例元数据端点以获取访问令牌。默认情况下，此令牌提供对客户项目中云存储的读取权限。
我搭建了一个 Autopilot 看了下，pod里也可以访问 metadata，不过没有文章所说的云存储权限
```bash
root@nginx-1-6f56f68fd8-b57j9:/# curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/scopes
https://www.googleapis.com/auth/cloud-platform
https://www.googleapis.com/auth/userinfo.email
```

2024-01-23 13:13 UTC, ssst0n3 commented on 2024-01-22_云漏洞案例_Unit42_GKE Autopilot 从容器逃逸到接管k8s集群并持久化后门.md
> +2. 攻击者可以查询节点的实例元数据端点以获取访问令牌。默认情况下，此令牌提供对客户项目中云存储的读取权限。
嗯嗯，我觉得这和本漏洞关系不大。如果metadata包含这样的敏感信息，那应该是metadata的一个单独的漏洞。而不是通过容器逃逸 == 可以读取云存储。

可以不用管，甚至删除这一行。

2024-01-23 13:56 UTC, tarimoe commented on 2024-01-22_云漏洞案例_Unit42_GKE Autopilot 从容器逃逸到接管k8s集群并持久化后门.md
> +2. 攻击者可以查询节点的实例元数据端点以获取访问令牌。默认情况下，此令牌提供对客户项目中云存储的读取权限。
是的 试过后确实是这么回事，我明天在改改

2024-01-24 00:59 UTC, tarimoe commented
@ssst0n3 review issue resolved

2024-01-24 01:32 UTC, tarimoe commented
> 一些疑问，留待研究：
> 
> * 为什么拒绝 External IP svc  可以防御 [CVE-2020-8554](https://github.com/advisories/GHSA-j9wf-vvm6-4r9w)
> * GKE autopilot 如何拒绝External IP svc (PSA? OPA?)
> * 也能防御 37c3 ctf 那道题的External IP svc 利用手法吗
> 
> > Autopilot's policy goes beyond preventing container escapes. Figures 3, 4, and 5 highlight a few interesting examples. [GKE's documentation](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#limits) lists every limit enforced by the policy.
> 
> 这个链接里貌似没有limits了，具体限制哪些还挺有意思

1. 看文章的时候有顺便了解了一下，https://github.com/kubernetes/kubernetes/issues/97076 这个 issue 有讨论，其实这个CVE是关于中间人攻击的，官方也没有patch，官方提供的缓解方式也是提供给用户一个webhook去限制，漏洞利用过程可以看漏洞挖掘者的博客，https://blog.champtar.fr/K8S_MITM_LoadBalancer_ExternalIPs/ ， svc 加了 External IP 应该在宿主机层面加了个 iptables，通过外部 IP 访问到 k8s 节点宿主机，会走 iptables 转发到添加了 External IP svc（比如 External IP 是公网IP，进入到 svc 或者 pod 时就能实现这个pod直接是暴露在公网到节点一样的效果） 。从节点内部去请求该外部 IP，实际上最终外部IP还是会走到k8s节点宿主机，流量会被网络插件或者 iptables 转发到相应添加了 External IP 的 svc，从而实现中间人攻击。所以如果创建 svc 指定 External IP 会报错，自然就不存在这个中间人攻击了
2. 拒绝External IP 是 OPA 文章有提到图5是，Gatekeeper作用
3. 估计是可以的，到时候我复现顺便试试
4. limit感觉和 fastjson 的后面版本的修复方式类似，把白名单和黑名单的包名取哈希，攻击者不知道，可以在一定程度上被研究绕过 2333

2024-01-24 04:54 UTC, ssst0n3 approved these changes
nice

2024-01-24 04:54 UTC, merged